### ISSUE TITLE
load softbody meshes

### ISSUE THREAD

**Issue by Yusufma03** [taichi-dev/taichi_three#19]
Hi, thanks a lot for the great work! I'm wondering if it is possible to load a deformable object from a .obj file?

**Comment by archibate** [comment]
Yes it's possible. All data loaded into T3 can be modified at each frame for creating an animation of deformation.
See https://github.com/taichi-dev/taichi/blob/master/examples/mass_spring_3d.py for example:
![image](https://github.com/taichi-dev/public_files/raw/master/taichi/mass_spring_3d.gif)

**Comment by Yusufma03** [comment]
Got it. Thanks!
