### ISSUE TITLE
Try run mass_spring_3d.py failed with AssertionError

### ISSUE THREAD

**Issue by Iteravse** [taichi-dev/taichi_three#20]
frist time i run [mass_spring_3d.py](https://github.com/taichi-dev/taichi/blob/master/examples/mass_spring_3d.py) demo reminds me need taichi_three,after installed run again,it pops the error like this:

```
[Taichi] mode=release
[Taichi] version 0.6.37, llvm 10.0.0, commit e0ac1d86, win, python 3.8.5
[TaiGLSL] version 0.0.10
[Tai3D] version 0.0.5
[Tai3D] Inputs are welcomed at https://github.com/taichi-dev/taichi_three
[Tai3D] Camera control hints: LMB to orbit, MMB to move, RMB to scale
Traceback (most recent call last):
  File "D:/python/Anaconda3/envs/XEngine/Lib/site-packages/taichi/examples/mass_spring_3d.py", line 9, in <module>
    assert t3.__version__ == (0, 0, 3)
AssertionError

Process finished with exit code 1
```
how to solve this problem? and btw i installed taichi_glsl too

**Comment by archibate** [comment]
Sorry for the confusing error message here, you may need to downgrade taichi_three to v0.0.3 by executing:
```
python3 -m pip install taichi_three==0.0.3
```

**Comment by Iteravse** [comment]
> Sorry for the confusing error message here, you may need to downgrade taichi_three to v0.0.3 by executing:
> 
> ```
> python3 -m pip install taichi_three==0.0.3
> ```
unfortunately,then i encounter another error:

```
Traceback (most recent call last):
  File "D:/python/Anaconda3/envs/XEngine/Lib/site-packages/taichi/examples/mass_spring_3d.py", line 62, in <module>
    model = t3.Model(f_n=(N - 1)**2 * 4, vi_n=N**2, vt_n=N**2, f_m=1)
  File "D:\python\Anaconda3\envs\XEngine\lib\site-packages\taichi_three\model.py", line 15, in __init__
    self.L2W = Affine.var(())
AttributeError: type object 'Affine' has no attribute 'var'
```
btw how to realize fullscreen show in taichi?i can't find the option of gui in document,just change the resolution to 1920*1080 and still having title bar,any good advice?

**Comment by archibate** [comment]
> unfortunately,then i encounter another error:

Oh I see, does https://github.com/archibate/taichi/blob/upgrade-ms-cloth-005/examples/mass_spring_3d.py with `pip install taichi_three==0.0.5` work?

> btw how to realize fullscreen show in taichi?

Actually our GUI don't support fullscreen at this moment.. Use an external GUI package for display like `PyOpenGL` if you need that, and interface with Taichi using `pixels.to_numpy()`.

**Comment by archibate** [comment]
> btw how to realize fullscreen show in taichi?i can't find the option of gui in document,just change the resolution to 1920*1080 and still having title bar,any good advice?

This new feature is WIP in https://github.com/taichi-dev/taichi/pull/1921, thank for the cool idea!

**Comment by Iteravse** [comment]
> Oh I see, does https://github.com/archibate/taichi/blob/upgrade-ms-cloth-005/examples/mass_spring_3d.py with `pip install taichi_three==0.0.5` work?

great it worked ! , so beautiful effect !

> This new feature is WIP in taichi-dev/taichi#1921, thank for the cool idea!

that will be fantastic!,waiting you good news
