### ISSUE TITLE
default_fp=ti.f64 leading to warning

### ISSUE THREAD

**Issue by squarefk** [taichi-dev/taichi_three#25]
Shall we use something like 'ti.get_runtime().default_fp' to make this consistent and avoid unnecessary warning?
Or there is some performance issue for the render where it has to use float. We could add some type conversion I guess.

**Comment by archibate** [comment]
What's the warning message actually? Does it still exist in latest Taichi?

**Comment by squarefk** [comment]
For the latest version, no. We could temporarily close this.
