### ISSUE TITLE
screen_to_texcoor.py triggers error

### ISSUE THREAD

**Issue by DenisTome** [taichi-dev/taichi_three#28]
Vanilla `screen_to_texcoor.py` returns the following error:
```bash
File "examples/screen_to_texcoor.py", line 41, in <module>
	mid = gbuff.fetchpixelinfo('mid', coor)
File HOME/anaconda3/envs/dl/lib/python3.7/site-packages/taichi_three/buffer.py", line 91, in fetchpixelinfo
	return self[name][I].value
AttributeError: 'int' object has no attribute 'value'
```

**Configuration**
OS: Ubuntu 18.04
taichi_three version: v0.0.9
Python version: 3.7.1

**Comment by archibate** [comment]
Thank for reporting! This is now being fixed in latest `master`.
You may clone this repo and install it locally or wait for the v0.0.10 release to get this script work.
