### ISSUE TITLE
Camera model

### ISSUE THREAD

**Issue by DSaurus** [taichi-dev/taichi_three#7]
I notice that now the camera model is imperfect and I want to write new camera models.
But I have a problem about Z-Buffer and rendering process. Why does it use "max" rather than "min"?

**Comment by archibate** [comment]
Maybe it's because the `zbuf` is initialized to be zero? Not sure if this works for > 3 conflicts... we may want to use `1/z` instead for "min" Z-buffering?

**Comment by DSaurus** [comment]
> Maybe it's because the `zbuf` is initialized to be zero? Not sure if this works for > 3 conflicts... we may want to use `1/z` instead for "min" Z-buffering?

OK, I understand it, I will try to write the new camera models based on '1/z' Z-buffering.
